### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by seungyun1** [ddetommaso/TobiiGlassesPySuite-Examples#1]
Hello
Of the example codes you've posted on 'PySuite',
aoi_gmm, aoi_surf, aoi_dbscan
To run the file:
This error has occurred(picture attached)
![메일](https://user-images.githubusercontent.com/69844293/126953565-1485b79f-0814-4e89-8388-607f0e23bf07.png)

The errors are :
When I import tobiiglasses/aoi/clustering.py file,
1)  can not import imread from scipy.misc
2) ModuleNotFoundError : No module named 'model'

When I looked it up, the module 'model' didn't exist.
If there is any change, could you modify it so that I can run the code?

Thank you so much!

**Comment by rajshekarreddy97** [comment]
I'm getting the same error. Has there been a fix for this?

**Comment by ddetommaso** [comment]
Thank you for opening the issue and sorry for the delay. The issue should be gone with the latest version.
